<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
  const CLASS_NAME = 'Contact';

  public static function getInstance()
  {
    return Doctrine_Core::getTable(self::CLASS_NAME);
  }

//================================================================================================
// ■2. 新規登録
//================================================================================================
 /**
   * 新規登録
   * @param $data  
   */
  public function insertData($data)
  {
    $obj = new Contact();

    $obj->setName         ($data["name"]);  
    $obj->setMail         ($data["mail"]);  
    $obj->setComment      ($data["comment"]);  
    $obj->setCreatedAt    (date('Y-m-d H:i:s'));  
    $obj->save();
    
    return $obj;
  }

}