<?php

/**
 * Image2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Image2Table extends Doctrine_Table
{
  const CLASS_NAME = 'Image2';

  public static function getInstance()
  {
    return Doctrine_Core::getTable(self::CLASS_NAME);
  }

//================================================================================================
// ■1. 参照系
//================================================================================================
  /**
   * 一覧取得
   */
  public function getList($type)
  {
    $q = Doctrine_Query::create()
          ->select('i.*, p.name, p.url')
		      ->from("Image2 i")
		      ->leftJoin('i.Place p ON p.id = i.place_id')
					->andWhere('i.type = ?',  $type)
					->andWhere('i.delete_flag = ?',  '0')
					->addOrderBy('i.place_id asc, i.img_no')
					; 

    $ret = $q->fetchArray();
    
    $ret_array = array();
    
    foreach($ret as $key => $value)
    {
      $ret_array[$value['place_id']][] = $value;
    }

    foreach($ret_array as $key => $value)
    {
	    shuffle($ret_array[$key]);
    }
  
    return $ret_array;
  }
  
//================================================================================================
// ■クエリ
//================================================================================================
  /**
   * 有効データ抽出クエリ
   */
  public function addActiveQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from(self::CLASS_NAME);
    }
 
    $q->andWhere('delete_flag = ?',    sfConfig::get('app_delete_flag_active'));
 
    return $q;
  }

}