<?php

/**
 * PlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlaceTable extends Doctrine_Table
{
  const CLASS_NAME = 'Place';

  public static function getInstance()
  {
    return Doctrine_Core::getTable(self::CLASS_NAME);
  }

//================================================================================================
// ■1. 参照系
//================================================================================================
  /**
   * リンク一覧取得
   */
  public function getLinkList($key='prefectureId', $dir='asc', $check_flag=false)
  {
    $q = Doctrine_Query::create()
      ->from(self::CLASS_NAME);

    if($check_flag == false)
    {
      $q = $this->addActiveQuery($q);
    }

    $q->andWhere('link_flag = ?',  '1');

    $q->addOrderBy($key . ' ' . $dir); 
    $q->addOrderBy('address '. $dir); 

    $ret = $q->fetchArray();
  
    return $ret;
  }
  
  /**
   * 全一覧取得（ID単位）
   */
  public function getAllList()
  {
    $q = Doctrine_Query::create()
      ->from(self::CLASS_NAME);

    $q = $this->addActiveQuery($q);

    $ret = $q->fetchArray();

    $ret_array = array();
    
    foreach($ret as $key => $value)
    {
      $ret_array[$value['id']]= $value;
    }

    return $ret_array;
  }

  /**
   * 各種件数取得
   */
  public function getCountArray()
  {
    $ret_array          = array();

    $ret    = Doctrine::getTable(self::CLASS_NAME)->getAllList();

    foreach($ret as $key => $value)
    {
      // 全件
      if(!isset($ret_array['total']))   $ret_array['total'] = 1;
      else                              $ret_array['total']++;  

      // 都道府県
      if(!isset($ret_array['pref'][$value['prefectureid']]))  $ret_array['pref'][$value['prefectureid']] = 1;
      else                                                    $ret_array['pref'][$value['prefectureid']]++;  

      // カテゴリ
      if($value['flag_care']==1)
      {
        if(!isset($ret_array['category']['flag_care']))   $ret_array['category']['flag_care'] = 1;
        else                                              $ret_array['category']['flag_care']++;  
      }
      if($value['flag_work']==1)
      {
        if(!isset($ret_array['category']['flag_work']))   $ret_array['category']['flag_work'] = 1;
        else                                              $ret_array['category']['flag_work']++;  
      }
      if($value['flag_art']==1)
      {
        if(!isset($ret_array['category']['flag_art']))  $ret_array['category']['flag_art'] = 1;
        else                                            $ret_array['category']['flag_art']++;  
      }
      if($value['flag_museum']==1)
      {
        if(!isset($ret_array['category']['flag_museum'])) $ret_array['category']['flag_museum'] = 1;
        else                                              $ret_array['category']['flag_museum']++;  
      }
      if($value['flag_product']==1)
      {
        if(!isset($ret_array['category']['flag_product']))  $ret_array['category']['flag_product'] = 1;
        else                                                $ret_array['category']['flag_product']++;  
      }
      if($value['flag_school']==1)
      {
        if(!isset($ret_array['category']['flag_school'])) $ret_array['category']['flag_school'] = 1;
        else                                              $ret_array['category']['flag_school']++;  
      }
      if($value['flag_publication']==1)
      {
        if(!isset($ret_array['category']['flag_publication']))  $ret_array['category']['flag_publication'] = 1;
        else                                                    $ret_array['category']['flag_publication']++;  
      }
      if($value['flag_food']==1)
      {
        if(!isset($ret_array['category']['flag_food']))   $ret_array['category']['flag_food'] = 1;
        else                                              $ret_array['category']['flag_food']++;  
      }
      if($value['flag_dance']==1)
      {
        if(!isset($ret_array['category']['flag_dance']))  $ret_array['category']['flag_dance'] = 1;
        else                                              $ret_array['category']['flag_dance']++;  
      }
      if($value['flag_other']==1)
      {
        if(!isset($ret_array['category']['flag_other']))  $ret_array['category']['flag_other'] = 1;
        else                                              $ret_array['category']['flag_other']++;  
      }
      if($value['flag_shop']==1)
      {
        if(!isset($ret_array['category']['flag_shop']))   $ret_array['category']['flag_shop'] = 1;
        else                                              $ret_array['category']['flag_shop']++;  
      }
      if($value['flag_seeing']==1)
      {
        if(!isset($ret_array['category']['flag_seeing'])) $ret_array['category']['flag_seeing'] = 1;
        else                                              $ret_array['category']['flag_seeing']++;  
      }
      if($value['flag_hearing']==1)
      {
        if(!isset($ret_array['category']['flag_hearing']))  $ret_array['category']['flag_hearing'] = 1;
        else                                                $ret_array['category']['flag_hearing']++;  
      }
    }

    return $ret_array;
  }

//================================================================================================
// ■クエリ
//================================================================================================
  /**
   * 有効データ抽出クエリ
   */
  public function addActiveQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from(self::CLASS_NAME);
    }
 
    $q->andWhere('delete_flag = ?',    sfConfig::get('app_delete_flag_active'));
 
    return $q;
  }


}