<?php

/**
 * WordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WordTable extends Doctrine_Table
{
  const CLASS_NAME = 'Word';

  public static function getInstance()
  {
    return Doctrine_Core::getTable(self::CLASS_NAME);
  }
  
//================================================================================================
// ■1. 参照系
//================================================================================================
  /**
   * 一覧取得
   */
  public function getList($placeId, $commentType='', $limit='0', $offset='0')
  {
/*  $table = Doctrine_Core::getTable(self::CLASS_NAME);
    $con = $table->getConnection();
    $con->execute("SET @no = 0;");*/

    $q = Doctrine::getTable(self::CLASS_NAME)->addActiveQuery();
    $q->select  ('*, @no := @no + 1 AS no');
    $q->andWhere('place_id = ?',      $placeId);
    $q = $this->addActiveQuery($q);
    
    if($commentType)
    {
      $q->andWhere('comment_type = ?',  $commentType);
    }

    if($limit)
    {
      $q->limit($limit);
    }
    
    if($offset)
    {
      $q->offset($offset);
    }
    
    $q->addOrderBy('posted_at DESC, created_at DESC'); 

    $ret = $q->fetchArray();
    //echo $q->getSqlQuery()."\n"; echo "<pre>"; print_r($ret); echo "</pre>";exit;
    
    $ret_array = array();
    $no_array  = array("1"=>"1"+$offset,"2"=>"1"+$offset,"3"=>"1"+$offset,"4"=>"1"+$offset);
    
    foreach($ret as $key => $value)
    {
      $value["no"] = $no_array[$value['comment_type']];
      $ret_array[$value['comment_type']][] = $value;
      $no_array[$value['comment_type']]++;
    }
    //echo $q->getSqlQuery()."\n"; echo "<pre>"; print_r($ret_array); echo "</pre>";exit;
   
    return $ret_array;
  }

  /**
   * 件数取得
   */
  public function getCount($placeId, $commentType='')
  {
    $q = Doctrine::getTable(self::CLASS_NAME)->addActiveQuery();
    $q->andWhere('place_id = ?',      $placeId);
    
    if($commentType)
    {
      $q->andWhere('comment_type = ?',  $commentType);
    }

    $ret = $q->execute();
    return count($ret);
  }

//================================================================================================
// ■クエリ
//================================================================================================
  /**
   * 有効データ抽出クエリ
   */
  public function addActiveQuery(Doctrine_Query $q = null)
  {
    if (is_null($q))
    {
      $q = Doctrine_Query::create()
        ->from(self::CLASS_NAME);
    }
 
    $q->andWhere('delete_flag = ?',    sfConfig::get('app_delete_flag_active'));
 
    return $q;
  }

//================================================================================================
// ■2. 新規登録
//================================================================================================
 /**
   * 新規登録
   * @param $data  
   */
  public function insertData($data)
  {
    $obj = new Comment();

    $obj->setPlaceId      ($data["place_id"]);  
    $obj->setName         ($data["name"]);  
    $obj->setMail         ($data["mail"]);  
    $obj->setComment      ($data["comment"]);  
    $obj->setCommentType  ($data["comment_type"]);  
    $obj->save();
    
    return $obj;
  }

//================================================================================================
// ■3. 更新系
//================================================================================================  
 /**
   * 更新
   */
  public function updateData($data)
  {
    $q = Doctrine_Query::create()
      ->update    (self::CLASS_NAME)
      ->set       ('updated_at',      '?',   date('Y-m-d H:i:s'))
      ->where     ('id = ?',  $data["id"])
      ;
      
    $q->execute();    
  }
}